name: Manual Workflow Trigger

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: chatgpt
        id: chatgpt
        uses: Swapnil-Devops/openai-gpt3-action@main
        with:
          API_KEY: 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
          PROMPT: what is GitHub?
