name: Update Discussion on Comment

on:
  discussion_comment:
    types:
      - created
jobs:
  update-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get discussion information
        id: discussion-info
        run: |
           echo "comment_body=$(echo '${{ toJson(github.event) }}' | jq '.comment.body')" >> $GITHUB_OUTPUT
           echo "disc_number=$(echo '${{ toJson(github.event) }}' | jq '.discussion.number')" >> $GITHUB_OUTPUT

      - name: Get Blurb discussion number
        id: blurb_disc_number
        run: |
           echo "blurb_disc_number= ${{ steps.discussion-info.outputs.disc_number }}+1 "      
      
        
