name: Update Discussion on Comment

on:
  discussion_comment:
    types:
      - created
jobs:
  update-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get discussion information
        id: discussion-info
        run: |
           echo '${{ toJson(github.event)}}'
      
        
